### ISSUE TITLE
Issue tracker for test migration

### ISSUE THREAD

**Issue by kbx81** [esphome/issues#5479]
### The problem

As I'm moving tests, I'm finding some issues. This GH issue is a tracker for them; it will not go into specific details, it's just a list of things that either didn't (but probably should) work or that we need to circle back on for completeness. I'll continue to update it as I uncover more.

- [ ] `exposure_notifications` [example in doc](https://next.esphome.io/components/exposure_notifications) is broken
- [ ] `fastled` and `neopixelbus` components need to be built with older version of Arduino (on 8266?)
- [ ] `lightwaverf` only builds on 8266 but doesn't validate for it
- [x] How do we test `host` platform?
- [x] Testing for `libertiny` components/processors
- [ ] `media_player` requires wifi (?) but doesn't check for it
- [ ] `midea` requires wifi (?) but doesn't check for it
- [ ] `sun` requires `time` but it's not documented
- [ ] `ufire` examples in docs don't work -- action names are incorrect, extra `temperature` variable in ISE component

### Which version of ESPHome has the issue?

2024.02.1-dev
